### PR TITLE
Cannot read property 'length' of undefined

### PR DESCRIPTION
**Pull request by bad4iz**

### CODE REVIEW

**Comment by nnarhinen** [comment]
Where is this a problem? Why do we need this check?

**Comment by bad4iz** [comment]
I have crashes if the buffer is bad.
> Cannot read property 'length' of undefined

**Comment by nnarhinen** [comment]
A correct fix would be to never trigger the buffer event without buffered parts.

**Comment by bad4iz** [comment]
how to do this?
I do this so
```javascript
flowplayer(`#jsplaylist${this.number}`, {
        muted: true,
        share: false,
        autoplay: true,
        disabled: true,
        live: true,
        // splash: true,
        clip: {
          sources: [{
            type: this.type,
            src: this.src,
          }],
        },
      }).on('load', () => {
       
        // do something when a new video is about to be loaded
      }).on('ready', () => {
     
        // do something when a video is loaded and ready to play
      }).on('error', (e, api) => {
       
      });
```

**Comment by nnarhinen** [comment]
As per contribution guidelines a link to the misbehaving setup is needed.

**Pull request closed without merging**
