### PR TITLE
Decrease chances for error on video tag seekable and buffered detection

### PR DESCRIPTION
**Pull request by blacktrash**

### CODE REVIEW

**Comment by blacktrash** [comment]
@nnarhinen - a bit pedantic, but may avoid the odd user distracting console error, and doesn't hurt too much.

**Comment by nnarhinen** [comment]
When can `videoTag.seekable` or `videoTag.buffered` be undefined?

It should always be a read-only property returning a `TimeRanges` object - https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/seekable

**Comment by blacktrash** [comment]
I don't know. I was inferring it from the old code: `arg.seekable = api.seekable && api.seekable.end(null);`
I can change it to use consistently `seekable.length` only instead.

**Comment by blacktrash** [comment]
otoh we also have a lot of those wrapped in try-catch blocks. I wonder why?

**Comment by blacktrash** [comment]
Tested with empty video tag and empty source tag, checking for length only seems ok.

**Comment by nnarhinen** [comment]
Closing this until we actually hit a problem with this.

**Pull request closed without merging**
