### PR TITLE
Wrap buttons in a container

### PR DESCRIPTION
**Pull request by nnarhinen**
Wraps all (upper-right corner) buttons in a container.

It will be the only absolutely positioned element in the upper-right
corner.

All buttons inside the container will flow freely. This will allow us to
be more flexible in adding / removing buttons without gaps etc.

### CODE REVIEW

**Comment by nnarhinen** [comment]
@blacktrash your comments here please.

In the end result inside `.fp-ui` there will be `<div class="fp-buttons"><a class="fp-embed"></a><a class="fp-fullscreen"></a></div>` etc

Do you see any problems with this for 6.1?

**Comment by nnarhinen** [comment]
I'm doing this because I'm planning on adding features that will add buttons to the upper-right corner and it will be a pain in the ass supporting all combinations of `is-` classes and absolute positioning of the buttons.

**Comment by blacktrash** [comment]
@nnarhinen - in theory I don't, quite to the contrary it makes a lot of sense.
In practice I haven't found the time to test because I was/am occupied with https://github.com/flowplayer/flowplayer/issues/1050 among other stuff, sorry.

**Comment by blacktrash** [comment]
Quick testing issue: Buttons are aligned on top of each other in fullscreen.

**Comment by nnarhinen** [comment]
@blacktrash the fullscreen issue should be gone now, can you confirm?

(http://demos.1049f.flowplayer.me/)

**Comment by blacktrash** [comment]
@nnarhinen - seems to work.
Will have to find out how to adapt http://demos.1049f.flowplayer.me/lookandfeel/fs-controlbar.html once it's out.

**Pull request merged**
