### PR TITLE
Autoplay on touch devices

### PR DESCRIPTION
**Pull request by nnarhinen**

### CODE REVIEW

**Comment by nnarhinen** [comment]
@blacktrash 

Please check http://demos.1227f.flowplayer.me/ for any regressions.

It:
 * enables first frame setups for Android & iOS devices
 * enables muted autoplay for these devices

**Comment by nnarhinen** [comment]
The player is unmuted only when first interaction with the player is done. This is how the native video tag also works.

**Comment by blacktrash** [comment]
Quick feedback:
- iOS looks OK (but I only check iOS 10)
- Android + hlsjs will be tricky: http://demos.1227f.flowplayer.me/basics/poster.html - Chrome has the expected problem with the required play nudge (if I use load, certain scenarios will error out w/o recovery - http://demos.flowplayer.org/api/live-check.html - which is why we unload on broken play promise) - Firefox does not initiate hlsQualities ... basically this exacerbates or extends this engine plugin problem: https://github.com/flowplayer/flowplayer-hlsjs/issues/50 (similarly for dashjs). I'll try to find out ways of dealing with this case from the plugin side (of course the plugins have to be kept backwards compatible as well ...).

**Comment by nnarhinen** [comment]
You need to set the `muted` attribute for the video tag in order to use `play()` or autoplay without user interaction.

**Comment by blacktrash** [comment]
I'm aware of the `muted` thing, I had this problem in mind: https://github.com/flowplayer/flowplayer-hlsjs/issues/50
This is needed for Android Chrome to "autoplay" hlsjs *with* user interaction: https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L855-L868 - it's also the reason why http://demos.flowplayer.org/api/live-check.html does not work on Android Chrome (so I implemented the play promise to at least unload properly, otherwise there's an unrescuable error state).

**Pull request merged**
